service: customer-authentication-function

frameworkVersion: "3.39"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource: "*"

plugins:
  - serverless-plugin-typescript

functions:
  customer-authentication:
    handler: src/handler.main
